### ISSUE TITLE
Back Up  adguardhome Configuration to Local 

### ISSUE THREAD

**Issue by WarlockFish** [bakito/adguardhome-sync#289]
### Is your feature request related to a problem? Please describe.

 I only have one adguardhome service and I would like to backup the configuration of the adguardhome to the local device 

### Describe the solution you'd like*

copy the config file to docker's  local  file

### Describe alternatives you've considered

copy the config file to local

### Anything else?

no

**Comment by bakito** [comment]
@WarlockFish theis Tool does not have access to the ardguardhome only API access. 

Adguardhome stores the config in `/opt/adguardhome/conf/AdGuardHome.yaml`.
 You can copy this file from the container with `docker cp` and mount it then back from your local dir.

Otherwise open an issue direct in adguardhome.
