### ISSUE TITLE
Sync DHCP leases between servers

### ISSUE THREAD

**Issue by Mattieug** [bakito/adguardhome-sync#294]
### Is your feature request related to a problem? Please describe.

Hello,
I don't understand how DHCP config works. If the 2 servers have the same config and they can be up at the same time (I know there is an option to enable/disable DHCP config sync).
And if the 2 servers are enabled, how active leases are managed ?
I am asking this because I am implementing a failover network and DHCP is the only component not yet redundant.
I would like Adguard sync to allow me have main and replica servers working together on the same ip scope.

Would it be possible ?

Thanks

### Describe the solution you'd like*

To have a synchronisation 2 ways of DHCP leases between servers

### Describe alternatives you've considered

The alternative is to split the scope between the 2 servers but not possible if more devices than IPs available.

### Anything else?

Just thank you for your work !

**Comment by bakito** [comment]
Hi @Mattieug 
I'm not a DHCP specialist, but as far as I know, it's not allowed to have multiple DHCP servers up the same time.
If you would need to sync leases, this would have to be a 2-way sync. Adguardhome-sync only supports one way origin -> replica.

2-way sync will not be a use case for this tool.

**Comment by tdkl** [comment]
Without 2-way sync this would be prone to clients having same IP's on both DHCP instances. Considering you're seeking a "failover", you would have multiple options though:

1) run two adguardhome instances, with both being active DNS and DHCP servers. Don't sync the DHCP ranges between them, set separate range on both of them. Both DNS IP's are pushed to clients with the DHCP lease and both are used for DNS queries. The downside is that you get DNS stats split between two instances, not on a single pane.

2) run two adguardhome instances, with both being active DNS and DHCP servers. Don't sync the DHCP ranges between them, set separate range on both of them. You create a VIP with keepalived, which gets set on the MASTER adguardhome instance, that IP is pushed to clients with the DHCP lease and is only one used for DNS queries. This way you get DNS stats on VIP instance at the time, which would be mostly the MASTER adguardhome instance. 

If MASTER is down, the BACKUP instance will contain the stats, but hopefully for just a short duration until MASTER becomes active and VIP is switched to it.  If MASTER is down, DHCP leases are still offered by the BACKUP adguardhome instance with its own DHCP range. If MASTER comes up and also DHCP with it, the clients with the BACKUP DHCP leases still continue to function with the VIP DNS IP, you wont see the hostname for them though, since DHCP leases were set on the BACKUP DHCP instance. When the leases expire, the MASTER DHCP instance will offer a new IP lease and you'll get full information about the hostname on the MASTER stats page.

BUT it can still happen that some clients will get a DHCP lease on the BACKUP DHCP instance this way and you'll get split stats when both adguardhome instances are active.

3) run two adguardhome instances, while only MASTER is being active DNS and DHCP server, but BACKUP instance container is stopped. Sync the adguardhome config.yaml file between them without using adguardhomesync (just regular rsync), where you change the DHCP range value after syncing using 'sed' to a range not used on the MASTER instance. 

You create a VIP with keepalived, which gets set on the MASTER adguardhome instance, that IP is pushed to clients with the DHCP lease and is only one used for DNS queries. Use a script listening to the adguardhome instance on MASTER, which in case it's not available, runs 'docker compose up -d' on the BACKUP instance. This way only one DHCP server is always active on the network and you won't get the scenario with split stats while both instances would be running like in option 2 above. You will only have split stats in case MASTER is down. When MASTER gets back up, the keepalived script will shutdown the adguardhome container on BACKUP (DNS will work over VIP in both cases anyway) and MASTER DHCP instance will continue to hand DHCP leases when they expire on clients which got their IP's from the BACKUP instance.

I find the option 3 to be more "robust" on the long run, if avoiding split stats is the end goal. But yes, without two-way syncing of active DHCP leases, only a workaround like this is possible. Hope this helps.

**Comment by Mattieug** [comment]
Hello,

thanks for your quick answers.

@tdkl, I like your 4 options ! Very interesting...

Finally, I had configured my system using option 1 before your answer which is the simplest and perhaps the more robust. The biggest issue is that I have to manually copy to main server, personalised rules when clicking on authorize on a blocked request in the replica server interface before it is removed by the sync. But not a big problem for daily usage. If stats are on the 2 servers, it's just a little more complicated to consult them but nothing impossible. I don't do it each morning...

Just before installing the DNS/DHCP failover, I had secured my router/gateway using keepalived. I am using OpenMPTCPRouter (a fork of openwert) used to do failover of internet access. The software routers are configured MASTER/BACKUP with a VIP, only IP known by the clients. It works nice !

Thanks,

Matt.
