### ISSUE TITLE
Questions on replicating an existing adguard home server to a newly created one

### ISSUE THREAD

**Issue by dmshimself** [bakito/adguardhome-sync#304]
### What happened?

I'm not sure which server is the origin and which is the replica described in the docs, so any advice appreciated.

On debian linux I'm following the steps after install.  My existing adguardhome server is on (say) 10.13.100.100 and is in regular use, working fine.  Port 80 gives the GUI and the setup port on :3000 no longer responds which I think is expected behaviour.

I've created a new adguardhome server on (say) 10.13.100.101 which hasn't been configured and responds fines on port :3000 for setup.

My impression is that ORIGIN would be 10.13.100.100 as that has the original, working adguardhome server config and REPLICA1 would be 10.13.100.101.  However in the setup for Linux/Mac, (extract listed below) the ORIGIN points to something that should respond on port 3000 and the REPLICA1 points to a server that should respond on port 80.

At first glance that seems to be the wrong way round and the REPLICA should point to the setup on the new server port 3000.

Just checking before trying the first replication.

### AdguardHome-Sync Version

go install github.com/bakito/adguardhome-sync@latest

### AdguardHome Version

v0.107.44

### Configuration

```shell
Not configured yet
```

### Relevant log output

```shell
Not configured yet
```

### Anything else?

This is the bit I'm referring to:

export LOG_LEVEL=info
export ORIGIN_URL=https://192.168.1.2:3000
export ORIGIN_USERNAME=username
export ORIGIN_PASSWORD=password
# export ORIGIN_COOKIE=Origin-Cookie-Name=CCCOOOKKKIIIEEE
export REPLICA1_URL=http://192.168.1.3
export REPLICA1_USERNAME=username
export REPLICA1_PASSWORD=password
# export REPLICA_COOKIE=Replica-Cookie-Name=CCCOOOKKKIIIEEE

**Comment by bakito** [comment]
hi @dmshimself 

Technically it does not matter on which port ardgaurdhome is running. Important is, that you use the correct port in the configuration.

So your 'old' instance is ORIGIN with port 80, and your new instance is the REPLICA1.

If you also would like to finally run your 2nd instance on port 80, you would have to manually setup that instance by accessing it on port 3000 and configure it to run on port 80. Then configure it as REPLICA1 on port 80.

If you use the autosetup feature on an uninitialized instance on port 3000, this port stays for later use and can not be changed. This is due to technical reasons of this sync tool.

**Comment by dmshimself** [comment]
Many thanks for that extra information, really appreciated and my replica is up and running :-)
