### ISSUE TITLE
Auto initialise should allow the setting of the adguard UI listening port

### ISSUE THREAD

**Issue by cooperaj** [bakito/adguardhome-sync#72]
**Is your feature request related to a problem? Please describe.**
When using auto initialise of an instance it should be possible to set the port of the UI as you can currently do in the normal setup wizard.

**Describe the solution you'd like**
A few things are possible:

  1. A setting for the intended port number. This would replace whatever was in the replica url.
  2. Using the port number specified (or implied i.e. with a http:// prefix) in the replica url.
  3. Syncing the port number from the origin instance.

In all 3 of the cases, if auto initialise is true and the adguard instance has not been initialised then the inital configuration and setup should take place at port 3000. I realise this will likely require some sort of probe to happen to figure out what port should be used for initial configuration.

**Describe alternatives you've considered**
Running the install manually and then not using the auto initialise feature.

**Comment by bakito** [comment]
I was trying this when implementing the auto-initialize.
The issue was to handle the port change in the same process, therefore I decided to skip it since when running in docker, ports anyway can be mapped to any outside port.
if really a different port would be needed the manual initial setup would also not be so much effort and the let adgaurdhome-sync do the final setup on this instance.

**Comment by cooperaj** [comment]
> since when running in docker, ports anyway can be mapped to any outside port

Unfortunately not if you're using mac/ipvlans or host networking, but yes I can see it would add a great deal of complexity to implement. Still it would definitely be a nice to have as it would allow spinning up new adguard instances in a very convenient way.
