### ISSUE TITLE
排除上游dns服务器

### ISSUE THREAD

**Issue by Somalia0932** [bakito/adguardhome-sync#73]
主adguard的上游DNS服务器配置如下：
119.29.29.29
168.95.192.1
192.168.10.10

我不想同步192.168.10.10，这个DNS仅限master可以访问到，其它adguard实例是无法访问192.16.10.10的。期待后续可以做个排除规则。

**Comment by bakito** [comment]
@Somalia0932 I'm sorry can you please describe your issue in english and provide some more details.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. What version of AdGuardHome sync used?
2. What version of AdGuardHome us used?
3. How does the configuration look?
4. What is the error message?

**Expected behavior**
A clear and concise description of what you expected to happen.

**Log Files**
If applicable, add log files or json responses from AdGuardHome to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by cooperaj** [comment]
Using google translate seems to work quite well (at least into English)

**Exclude upstream DNS servers**
The upstream DNS server configuration of the primary adguard is as follows:
119.29.29.29
168.95.192.1
192.168.10.10

I don't want to synchronize 192.168.10.10, this DNS is only accessible to the master, other adguard instances are not accessible to 192.16.10.10. I look forward to making an exclusion rule in the future.

**Comment by bakito** [comment]
I still do not get the issue here

**Comment by cooperaj** [comment]
I believe that @Somalia0932 wants to selectively sync upstream DNS servers, so that they can exclude the 192.168.10.10 address. Realistically I think the answer is to just not sync that field and manage it manually.

**Comment by bakito** [comment]
Yes, this makes sense.
Jusz disable the FEATURES_DNS_SERVERCONFIG=false feature
