### ISSUE TITLE
AGH v0.107.14 Breaking API Changes

### ISSUE THREAD

**Issue by dalkain** [bakito/adguardhome-sync#99]
**Describe the bug**
Starting from v0.107.14 there is a breaking change that makes adguardhome-sync fail:
![image](https://user-images.githubusercontent.com/34625175/193709285-1ed3778c-05d6-42cb-8746-bf5106483fab.png)

Causes the following error:
![image](https://user-images.githubusercontent.com/34625175/193709390-c1718217-8b6d-474a-bdc4-e7b1fe7f4433.png)

**To Reproduce**
- Update replica instance to v0.107.14 or above
- Make a change on your primary instance that would need to be synced to replica(s)
- Run adguardhome-sync

1. What version of AdGuardHome sync used? v0.4.7
2. What version of AdGuardHome is used?  v0.107.14 and above
3. How does the configuration look? N/A
4. What is the error message? See above

**Expected behavior**
API requests should specify their content-type as application/json to allow for syncing

**Log Files**
N/A

**Additional context**
N/A

**Comment by bakito** [comment]
@dalkain Thank you for reporting this issue. a fix is provided in https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.8
Please be aware, that v0.107.14 remains incompatible due to some inconsistent serverseide checks that are fixed in v0.107.15
See: https://github.com/AdguardTeam/AdGuardHome/issues/4970
